# Generated by Django 3.2 on 2022-06-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_users_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users_profile',
            new_name='user_profile',
        ),
    ]
