# Generated by Django 3.2 on 2022-06-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_auto_20220617_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='name',
        ),
    ]
