# Generated by Django 3.2 on 2022-06-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_auto_20220612_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE'), ('other', 'OTHER')], default='other', max_length=6),
        ),
    ]
