# Generated by Django 3.2 on 2022-06-13 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_profile', '0004_petprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='other', max_length=6),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
