# Generated by Django 3.2 on 2022-06-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_auto_20220613_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet',
            new_name='user',
        ),
    ]
