# Generated by Django 3.2 on 2022-06-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0007_auto_20220613_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='measurement_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='measurement_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='measurement_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
