# Generated by Django 3.2 on 2022-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0009_alter_usersprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='other', max_length=6),
        ),
    ]
